### ISSUE TITLE
How to set User ProxyUser Configurations

### ISSUE THREAD

**Issue by hoptical** [andlaz/hadoop-oozie#1]
Hi,
I need to set "**oozie.service.ProxyUserService.proxyuser.#USER#.hosts**" and "**oozie.service.ProxyUserService.proxyuser.#USER#.groups**" values for oozie. 

I want to do this for hue to make it possible to submit jobs in oozie but I couldn't find a solution like setting environment variable to set these configs for oozie in your dockerfile during running container or etc.
I mean something like:
`docker run -e oozie.service.ProxyUserService.proxyuser.hue.hosts=* andlaz/hadoop-oozie
`

Is there any solution?
Thanks.

**Comment by andlaz** [comment]
Hi @hoptical , i would create a docker image from this one, add a small bash script or even RUN in the Dockerfile, to ( e.g. with awk ) update your config files with values from envvars.

i'm sure you have your reasons for working with this, but i have to note there are probably much more robust solutions to bring up oozie ( airflow? ) in a containerized environment, by now.

Good luck.
